
import React from 'react';

export const LZC_OPTIONS = [
  { value: "1108", label: "Abi Shah" }, { value: "1177", label: "Adokay" }, { value: "1277", label: "Ajoo" },
  { value: "1280", label: "Amlok Dar" }, { value: "1149", label: "Andhery" }, { value: "1155", label: "Anwar Abad" },
  { value: "1225", label: "Areef" }, { value: "1123", label: "Asbanr Bazar" }, { value: "1167", label: "Assegi Darra" },
  { value: "1161", label: "Asselo" }, { value: "1205", label: "Atto" }, { value: "1206", label: "Baba Gam" },
  { value: "1227", label: "Badalzo" }, { value: "1243", label: "Badin Ganderai" }, { value: "1100", label: "Badwan Bala" },
  { value: "1109", label: "Badwan Payeen" }, { value: "1290", label: "Bagh" }, { value: "1207", label: "Bagh Dalgram" },
  { value: "1267", label: "Bajouro" }, { value: "1258", label: "Balooda" }, { value: "1121", label: "Bambolai Bala" },
  { value: "1279", label: "Banda" }, { value: "1273", label: "Bandagai Talash" }, { value: "1235", label: "Banrr" },
  { value: "1185", label: "Barkalay Sher Colony" }, { value: "1215", label: "Barkhanai" }, { value: "1169", label: "Baroon" },
  { value: "1105", label: "Batan" }, { value: "1226", label: "Bazarak" }, { value: "1200", label: "Bishgram" },
  { value: "1166", label: "Biyarai" }, { value: "1247", label: "Bokrai" }, { value: "1135", label: "Buchakay" },
  { value: "1110", label: "Chakdara Khass" }, { value: "1111", label: "Chat Pat" }, { value: "1130", label: "Chekho" },
  { value: "1201", label: "Chinar Kot" }, { value: "1294", label: "Danwa" }, { value: "1192", label: "Dapor" },
  { value: "1099", label: "Darbar Chakdara" }, { value: "1147", label: "Darmal Payeen" }, { value: "1204", label: "Daro" },
  { value: "1122", label: "Darra" }, { value: "1265", label: "Dehrai" }, { value: "1195", label: "Dhall Gall" },
  { value: "1241", label: "Dinjarai" }, { value: "1148", label: "Dogai" }, { value: "1202", label: "Dokrai Khan Abad" },
  { value: "1295", label: "Fazal Abad" }, { value: "1101", label: "Gaddar" }, { value: "1236", label: "Gawardesh" },
  { value: "1170", label: "Gawnai" }, { value: "1257", label: "Ghwar Band" }, { value: "1163", label: "Ghwargay" },
  { value: "1232", label: "Gosam" }, { value: "1230", label: "Gudar Bakro" }, { value: "1106", label: "Gul Abad" },
  { value: "1194", label: "Gumbat" }, { value: "1197", label: "Gumbatay" }, { value: "1140", label: "Hajji Abad" },
  { value: "1168", label: "Haya Serai" }, { value: "1248", label: "Jabagai" }, { value: "1242", label: "Juni Kaly" },
  { value: "1187", label: "Kahll Barkaly" }, { value: "1256", label: "Kakas" }, { value: "1117", label: "Kamala" },
  { value: "1176", label: "Kamar Tall" }, { value: "1253", label: "Kambat" }, { value: "1183", label: "Kandaro" },
  { value: "1178", label: "Kandawono" }, { value: "1199", label: "Kargha Khazana" }, { value: "1208", label: "Kas Bucha Khail" },
  { value: "1282", label: "Kass Shamshi Khan" }, { value: "1286", label: "Katan Payeen" }, { value: "1103", label: "Khadagzai" },
  { value: "1118", label: "Khairabad" }, { value: "1172", label: "Khall" }, { value: "1115", label: "Khanpur" },
  { value: "1260", label: "Kharkay" }, { value: "1218", label: "Khazana" }, { value: "1143", label: "Kheema" },
  { value: "1229", label: "Khuna Packat" }, { value: "1269", label: "Khungi" }, { value: "1133", label: "Kityarrai" },
  { value: "1151", label: "Kohairay" }, { value: "1153", label: "Kot Bala" }, { value: "1107", label: "Kotigram" },
  { value: "1190", label: "Kotkay Lal Qilla" }, { value: "1228", label: "Kotkay Munda" }, { value: "1156", label: "Kotkay Rabat" },
  { value: "1240", label: "Kotki Shahi Khail" }, { value: "1160", label: "Koto" }, { value: "1171", label: "Koz Kaly Khall" },
  { value: "1250", label: "Kulalan" }, { value: "1203", label: "Kumbar" }, { value: "1104", label: "Kumbar Adenzai" },
  { value: "1142", label: "Lajbook" }, { value: "1196", label: "Lal Qilla" }, { value: "1137", label: "Larram" },
  { value: "1246", label: "Leekor" }, { value: "1175", label: "Luqman Banda" }, { value: "1211", label: "Machla" },
  { value: "1291", label: "Macho Talash" }, { value: "1191", label: "Maidan Bandai" }, { value: "1224", label: "Makhai" },
  { value: "1285", label: "Malak Abad" }, { value: "1139", label: "Malakan Payeen" }, { value: "1157", label: "Malakand Bala" },
  { value: "1263", label: "Manai" }, { value: "1162", label: "Mandish" }, { value: "1216", label: "Manyal" },
  { value: "1198", label: "Markhanai" }, { value: "1255", label: "Maskini" }, { value: "1131", label: "Mayar" },
  { value: "1238", label: "Mayar" }, { value: "1292", label: "Mian Banda" }, { value: "1114", label: "Mian Brangola" },
  { value: "1219", label: "Mian Kalay" }, { value: "1113", label: "Misyalawar" }, { value: "1144", label: "Morani" },
  { value: "1233", label: "Munda" }, { value: "1154", label: "Munjai" }, { value: "1220", label: "Musa Abad" },
  { value: "1209", label: "Nagotal" }, { value: "1284", label: "Nagrai" }, { value: "1213", label: "Namaz Kot" },
  { value: "1217", label: "Nambatai" }, { value: "1184", label: "Namseer" }, { value: "1272", label: "Nasafa Talash" },
  { value: "1132", label: "Nawagai Payeen" }, { value: "1288", label: "Naway Kaly" }, { value: "1237", label: "Nawe Kot" },
  { value: "1158", label: "Odigram" }, { value: "1119", label: "Osakai" }, { value: "1098", label: "Ouch Gharbi" },
  { value: "1102", label: "Ouch Sharqi" }, { value: "1268", label: "Paito Yar Khan Banda" }, { value: "1231", label: "Paloso Dag" },
  { value: "1278", label: "Pingal Inzaro" }, { value: "1244", label: "Qandahary" }, { value: "1222", label: "Qilla Shalkandai" },
  { value: "1275", label: "Qilla Shamashi Khan" }, { value: "1150", label: "Rabat" }, { value: "1234", label: "Rahim Abad Munda" },
  { value: "1249", label: "Rahim Abad Samarbagh" }, { value: "1112", label: "Ramorra" }, { value: "1138", label: "Rani" },
  { value: "1182", label: "Razagram" }, { value: "1254", label: "Sadbar Kay" }, { value: "1293", label: "Saddo" },
  { value: "1193", label: "Safaray" }, { value: "1173", label: "Safary Dooab" }, { value: "1174", label: "Sair" },
  { value: "1261", label: "Samarbagh" }, { value: "1245", label: "Sangi Para Qazi Abad" }, { value: "1159", label: "Sangolai Pyeeen" },
  { value: "1165", label: "Sangwali Bala" }, { value: "1164", label: "Sar Banda" }, { value: "1134", label: "Sehsada" },
  { value: "1120", label: "Shabaan" }, { value: "1128", label: "Shadam" }, { value: "1210", label: "Shagai" },
  { value: "1136", label: "Shahabad" }, { value: "1125", label: "Shahalam Baba" }, { value: "1264", label: "Shahi" },
  { value: "1179", label: "Shalfalam" }, { value: "1188", label: "Shalkanai" }, { value: "1262", label: "Sharbanai" },
  { value: "1124", label: "Shawa" }, { value: "1251", label: "Sheena Tangay" }, { value: "1152", label: "Shehzadai Bala" },
  { value: "1287", label: "Shekawlai" }, { value: "1146", label: "Sherkhanay" }, { value: "1239", label: "Shuttala" },
  { value: "1129", label: "Sia" }, { value: "1180", label: "Sia Gwanai" }, { value: "1270", label: "Siar" },
  { value: "1214", label: "Srafo Manzai" }, { value: "1281", label: "Srai Bala" }, { value: "1141", label: "Stanadar" },
  { value: "1259", label: "Swara Ghwanday" }, { value: "1223", label: "Takoro" }, { value: "1271", label: "Tangay" },
  { value: "1252", label: "Tangi Bala" }, { value: "1181", label: "Tango Kandawo" }, { value: "1266", label: "Tauda Cheena" },
  { value: "1126", label: "Tazagram" }, { value: "1116", label: "Tiknai Bala" }, { value: "1289", label: "Timergara 1" },
  { value: "1274", label: "Timergara 2" }, { value: "1127", label: "Tindodog" }, { value: "1221", label: "Toor Qilla" },
  { value: "1186", label: "Toormang" }, { value: "1283", label: "Uttala" }, { value: "1145", label: "Watangay Payeen" },
  { value: "1276", label: "Ziarat Talash" }, { value: "1212", label: "Zimdara" }, { value: "1189", label: "Zoor Mandi" }
];

export const HOSPITAL_OPTIONS = [
  { value: "1", label: "IRNUM Hospital, Peshawar" },
  { value: "2", label: "Government Lady Reading Hospital (General), Peshawar" },
  { value: "4", label: "Khyber Teaching Hospital Peshawar" },
  { value: "5", label: "Hayatabad Medical Complex Peshawar, Peshawar" },
  { value: "7", label: "Institute of Nuclear Medicine Oncology & Radiotherapy (INOR), Abbottabad" },
  { value: "8", label: "Institute Of Kidney Diseases, Hayatabad, Peshawar" },
  { value: "9", label: "Sarhad Jail Hospital for Psychiatric Diseases, Peshawar" },
  { value: "10", label: "Khyber Eye Foundation Hospital Peshawar" },
  { value: "11", label: "Bannu Institute of Nuclear Medicine Oncology & Radiotherapy (BINOR)" },
  { value: "12", label: "Dera Ismail Khan Institute of Nuclear Medicine & Radiotherapy (DINAR)" },
  { value: "14", label: "Swat Institute of Nuclear Medicine, Oncology & Radiology Swat (SINOR)" },
  { value: "16", label: "Ayub Teaching Hospital, Abbottabad." },
  { value: "17", label: "AIMS Diabetic Hospital, Hayatabad Peshawar" },
  { value: "18", label: "Frontier Foundation and Blood Transfusion, Peshawar." },
  { value: "19", label: "Fatimid Foundation Blood Bank Peshawar." },
  { value: "20", label: "Hamza Foundation and Blood Transfusion, Peshawar." },
  { value: "21", label: "Kuwait Teaching Hospital Peshawar" },
  { value: "25", label: "Al-Shifa Trust Eye Hospital Kohat" },
  { value: "27", label: "Mardan Medical Complex" },
  { value: "29", label: "Bacha Khan Medical Complex, Swabi" },
  { value: "30", label: "Khalifa Gul Nawaz Hospital Bannu" },
  { value: "31", label: "Peshawar Institute of Cardiology Hayatabad Peshawar" },
  { value: "33", label: "THQ Chakdara (Only for Dialaysis)" },
  { value: "34", label: "Telha Foundation Hospital Karak" },
  { value: "35", label: "THQ, Dargai" }
];

export const MOCK_POSTS = [
  {
    id: "1",
    title: "Public Health Update 2025",
    excerpt: "General updates on healthcare policies for the upcoming fiscal year.",
    content: "Full content about public health policies and community outreach programs designed to help those in need.",
    date: "2025-05-10",
    author: "Admin",
    isPrivate: false
  },
  {
    id: "2",
    title: "[PRIVATE] Mustahiq Registry Guidelines",
    excerpt: "Confidential internal document for LZC officers regarding registry updates.",
    content: "This document outlines the specific criteria for Zakat eligibility and the updated verification process for 2025-26. Only authorized personnel should access these details.",
    date: "2025-05-11",
    author: "Internal Audit",
    isPrivate: true
  },
  {
    id: "3",
    title: "[PRIVATE] Hospital Budget Allocation",
    excerpt: "Detailed breakdown of quarterly budgets for DHQ, THQ, and BHU facilities.",
    content: "A comprehensive spreadsheet and report detailing the exact funds available for patient expenses across all registered districts. This ensures transparency in fund distribution.",
    date: "2025-05-12",
    author: "Finance Dept",
    isPrivate: true
  }
];
